version: '3.8'
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    volumes:
      - ./server/config.ini:/config.ini

  test:
    container_name: test
    image: alpine:latest
    networks:
      - testing_net
    depends_on:
      - server
    environment:
      - SERVER_IP=server
      - SERVER_PORT=12345
    volumes:
      - ./validar-echo-server.sh:/validar-echo-server.sh
    command: sh -c "apk add --no-cache netcat-openbsd && sh /validar-echo-server.sh"


networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
